resilience4j.circuitbreaker:
 instances:
  loginUser:
   failureRateThreshold: 50
   minimumNumberOfCalls: 5
   waitDurationInOpenState: 60s
   permittedNumberOfCallsInHalfOpenState: 3
   automaticTransitionFromOpenToHalfOpenEnabled: true